project:
  type: website
  resources: 
    - "*.html"

website:
  title: "Rcambier's Blog"
  site-url: https://rcambier.github.io
  favicon: logo.png
  navbar:
    left: 
      - text: "Artificial Intelligence"
        file: artificial_intelligence.qmd
      - text: "Computer Science"
        file: computer_science.qmd
      - text: "Riddles"
        file: riddles.qmd
      - text: "Projects"
        file: projects.qmd
    right:
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    canonical-url: true



